### ISSUE TITLE
I'd suggest add a variable/Macro to switch leaks finder on or off

### ISSUE THREAD

**Issue by robyzhou** [Zepo/MLeaksFinder#1]
Hi,

It's a wonderful util to me to find my memory leaks in my APP, it's really useful!

I'd like to suggest add a variable/Macro to switch leaks finder on or off, you know in release package, it's needless to throw a exception to exit the app due to memory leak, but during debug.

Thanks a lot!

roby

**Comment by Zepo** [comment]
Thanks for your suggestion. Currently MLeaksFinder is on under debug mode only, and has NO effect in your release package.

**Comment by robyzhou** [comment]
@Zepo Thanks for your reply!
