### ISSUE TITLE
 UIImagePickerController with MLeaksFinder,crash no reasonable. i need help~~

### ISSUE THREAD

**Issue by Mjiulee** [Zepo/MLeaksFinder#13]
#pragma mark -
#pragma mark -UIImagePickerController
- (void)jumpToCameraOrPhotoLibraryWithType:(UIImagePickerControllerSourceType)type{
    UIImagePickerController *imagePickerController = [[UIImagePickerController alloc] init];
    imagePickerController.delegate      = self;
    imagePickerController.allowsEditing = YES;
    imagePickerController.sourceType    = type;
    [self presentViewController:imagePickerController animated:YES completion:^{}];
}

// callback
- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info
{
    UIImage *image = [info objectForKey:UIImagePickerControllerEditedImage];
    self.imagUAvrtar.image = image;
    self.img2upload= image;
    [picker dismissViewControllerAnimated:YES completion:^{}];
}

- (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker{
    [self dismissViewControllerAnimated:YES completion:^{}];
}

**Comment by Zepo** [comment]
It seems that UIKit has kept the UINavigationBar even after dismissing the UIImagePickerController and we don't know why. Just add 'UINavigationBar to the white list to fix this issue'.

**Comment by AmyLee91** [comment]
I met the same ,how do you solved
