### ISSUE TITLE
话说View栈区出来的时候，能带内存地址吗？

### ISSUE THREAD

**Issue by ColinHwang** [Zepo/MLeaksFinder#15]
最通过莫过于，知道泄漏问题，但是找不到。。。

**Comment by Zepo** [comment]
带内存地址好像也帮不了什么忙

**Comment by Zepo** [comment]
当发现内存泄漏时，有几种方法可以帮忙定位造成泄漏的原因：
1. 用 Instrument 的 Allocation 查看是谁持有对象的强引用。如果对象的 retain, release 次数较多，可能不大容易定位；
2. 可以用 facebook 的开源组件 FBRetainCycleDetector 检查有没有循环引用，我们的项目已经在试用了，但目前效果还不是特别好，还在继续探索中；

加内存地址的方法好像没有帮助，平时更多地要靠经验积累，才能快速定位到问题所在。

**Comment by ColinHwang** [comment]
感谢回复，期待探索后博客新文章。
