### ISSUE TITLE
在button 的点击事件或者UITableview 的点击Cell的事件中调用self.navigationController popViewControllerAnimated:YES 时就报没有释放

### ISSUE THREAD

**Issue by ranshon** [Zepo/MLeaksFinder#16]
在button 的点击事件或者UITableview 的点击Cell的事件中调用self.navigationController popViewControllerAnimated:YES 时就报没有释放

**Comment by Zepo** [comment]
![af597082-dbcd-11e5-9841-c1687f946a6a](https://cloud.githubusercontent.com/assets/11935315/15113696/7618a6c2-1628-11e6-97b9-875fd529c2d1.jpeg)

由堆栈可看出，被 UITouch 持有了，需要等到下次点击事件的时候才释放。这种情况需要特殊处理一下，是个 bug。

只有在 iOS9.2 及以前才有这个问题，在 iOS9.3 UIButton 已经及时释放。

**Comment by ranshon** [comment]
程序怎么处理，不用管吗

**Comment by Zepo** [comment]
这个得研究一下怎么处理了，算是 MLeaksFinder 的 bug。你可以先把 UIButton 加到白名单。

**Comment by ColinHwang** [comment]
原来如此，之前还在纠结这个问题。

**Comment by Zepo** [comment]
Fixed.
