### ISSUE TITLE
我自定义导航栏返回按钮自己写pop 事件， 来回的跳转几次就报错误

### ISSUE THREAD

**Issue by ranshon** [Zepo/MLeaksFinder#17]
我自定义导航栏返回按钮自己写pop 事件， 来回的跳转几次就报错误

**Comment by Zepo** [comment]
用的是最新代码吗？

**Comment by Zepo** [comment]
昨晚刚 ci 了代码，fix 了这个 bug，可以用最新代码试一下，如果还有问题，麻烦反馈一下。Pod 还没更新。

**Comment by ranshon** [comment]
我用的最新的代码啊

**Comment by Zepo** [comment]
能否贴一下详细信息？自定义导航栏的代码，还有报泄漏的信息。

**Comment by ranshon** [comment]
- (void)setNavi {
    UIButton *backBtn = [UIButton buttonWithType:UIButtonTypeCustom];
    backBtn.frame = ReturnRect;
    [backBtn setImage:[UIImage imageNamed:@"返回"] forState:UIControlStateNormal];
    [backBtn addTarget:self action:@selector(OnBackBtn:) forControlEvents:UIControlEventTouchUpInside];
    self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc]initWithCustomView:backBtn];
}


- (void)OnBackBtn:(UIButton *)btn {
    [self.navigationController popViewControllerAnimated:YES];
}


没法贴图：
Thread 1:EXC_BAD_ACCESS(code=1,address=0x0)

**Comment by Zepo** [comment]
麻烦 View-ViewController stack 贴一下？

**Comment by ranshon** [comment]
[http://weibo.com/1963157737/DvaaHhyJg](url)  没地方放图放这个链接了

**Comment by ranshon** [comment]
http://weibo.com/1963157737/DvaaHhyJg

**Comment by Zepo** [comment]
Fixed 了，试一下？
