### ISSUE TITLE
MLeaksFinder 老是检测到UIView对象未释放，如何继续排错

### ISSUE THREAD

**Issue by Suninus** [Zepo/MLeaksFinder#22]

**Comment by Zepo** [comment]
能否贴出泄漏信息？

**Comment by Suninus** [comment]
In case that UIView should not be dealloced, override -willDealloc in UIView by returning NO.
View-ViewController stack: (
    NewsCommentsDetailViewController,
    UIView
)

**Comment by Suninus** [comment]
一般而言, view单独泄漏的情况还是比较少的, 虽然也出现过, 但是总体而言都是viewController的泄漏连带了view的泄漏.

**Comment by Zepo** [comment]
先确定一下是不是误判，如果不是误判，定位问题的方法参照: https://github.com/Zepo/MLeaksFinder/issues/15

你这个场景误判的可能性很小，可以先把 MLeaksFinder 关了（最新代码有个宏可以关），然后在 dealloc 里加断点。

**Comment by Zepo** [comment]
从贴出来的信息看 viewController 已经成功释放，泄漏的是 view

**Comment by Suninus** [comment]
FBRetainCycleDetector 这个没检测到

**Comment by Suninus** [comment]
感谢回复，期待探索后博客新文章。

**Comment by Suninus** [comment]
感谢回复，期待探索后博客新文章。

**Comment by sukeyang** [comment]
请问问题解决了吗?我也遇到这个问题了
