### ISSUE TITLE
实际使用过程中controller存在有误报现象

### ISSUE THREAD

**Issue by edwardean** [Zepo/MLeaksFinder#23]
controller中若有网络请求的话，网络请求的block回调中一般都是直接引用self变量的，这样就导致controller除非在网络请求的block落地之前是不会被析构的，如果在这之前页面被pop掉，很容易出现误报

**Comment by Zepo** [comment]
这种情况属于释放不及时，既然 controller 已经被 pop 了，网络请求回来后就不应该执行 controller 相关的操作，浪费 cpu。

建议在 block 外加用 __weak self，block 里再 __strong 一下。
