### ISSUE TITLE
想确认这个是不是误报？

### ISSUE THREAD

**Issue by bellchen** [Zepo/MLeaksFinder#24]
@Zepo 你好，烦请看下
代码比较简单，一个TableviewCell，里边只有一个label，特意在dealloc中加了NSLog输出：
以下是TableviewCell的代码：
![qq20160613-0 2x](https://cloud.githubusercontent.com/assets/4231046/15996895/b01902ca-315f-11e6-9420-f2bd28acd143.png)
以下是console的输出，明显看到dealloc有执行NSLog()
![qq20160613-1 2x](https://cloud.githubusercontent.com/assets/4231046/15996907/d5bb3318-315f-11e6-9717-05c0ca02a45c.png)

**Comment by Zepo** [comment]
![b7bf1af5-1590-4ca8-994c-32f3441b8f63](https://cloud.githubusercontent.com/assets/11935315/15998929/a51120d2-3174-11e6-96c8-673134981cc2.jpeg)
这里报的是 cell 底下的 UITableViewCellContentView，说明 cell 已经成功释放了，但 contentView 没有。

**Comment by bellchen** [comment]
的确如此，我把

> [_titleLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.centerY.equalTo(self.contentView);
            make.left.equalTo(self.contentView).offset(15);
        }];

改为
>[self.titleLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.centerY.equalTo(self.contentView);
            make.left.equalTo(self.contentView).offset(15);
        }];

变化的只是把_titleLabel 改为 self.titleLabel 就解决了。谢谢哈

**Comment by Zepo** [comment]
这样改不对的，在 getter  方法里不要用 self.xxx。

正确的改法应该是先用 __weak 指针指向 self.contentView，然后在 block 里先转 __strong 指针，再用。
