### ISSUE TITLE
在stroyboard里面使用的问题？

### ISSUE THREAD

**Issue by vjieshao** [Zepo/MLeaksFinder#3]
在实际项目中，用了MLeaksFinder，但在SB中发现了一个问题。例如：在页面A跳转到页面B。页面B中有一个按钮，点击按钮是返回到页面A，如果直接手势返回，不会有什么问题。如果是点击页面B中的按钮返回，就会断言说按钮没有释放掉。不知道什么问题，求解答，写了个demo： https://github.com/vjieshao/MLeaksFinderTest 谢谢！

**Comment by Zepo** [comment]
![c12ab3bd-ae2a-41ae-8a86-42ba01b67255](https://cloud.githubusercontent.com/assets/11935315/13311970/af597082-dbcd-11e5-9841-c1687f946a6a.jpeg)

由堆栈可看出，被 UITouch 持有了，需要等到下次点击事件的时候才释放。这种情况需要特殊处理一下，是个 bug。

**Comment by vjieshao** [comment]
那是要自定义一个UIButton然后重写willDealloc这个方法么？？

**Comment by Zepo** [comment]
自定义 UIButton 的方法给该工具的使用者很大负担，肯定是不好的。建议先把 UIButton 加入白名单，UIButton 基本上也不会造成循环引用。

**Comment by Zepo** [comment]
https://github.com/Zepo/MLeaksFinder/issues/16 描述比较清楚，先把该 issue 关掉
