### ISSUE TITLE
提示UITableViewCellContentView未释放（代码创建的tableview）

### ISSUE THREAD

**Issue by JavenZ** [Zepo/MLeaksFinder#30]
我也遇到了，用的系统样式自带的cell，在返回cell的方法如下：
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:kCellId forIndexPath:indexPath];
    VankeShopModel *shop = self.results[indexPath.row];
    cell.textLabel.text = [NSString stringWithFormat:@"%@【%@】", shop.name, shop.code];
    return cell;
}

MLeakFinder提示：
Possibly Memory Leak.
In case that UITableViewCellContentView should not be dealloced, override -willDealloc in UITableViewCellContentView by returning NO.
View-ViewController stack: (
    ChooseShopViewController,
    UIView,
    UITableView,
    UITableViewWrapperView,
    UITableViewCell,
    UITableViewCellContentView
)

实在找不到哪里有内存泄露，希望对你完善框架有帮助。
PS:框架非常赞 : )

**Comment by Zepo** [comment]
能否给个完整个程序？

**Comment by RITL** [comment]
我也是遇到这种情况，但是cell的dealloc方法确实走了0.0，我该怎么办0.0

**Comment by Zepo** [comment]
能否提供个简化后的可重现问题的代码，不能没法帮忙定位问题。

**Comment by RITL** [comment]
您好，我试着做了一个小的复现，放到了https://github.com/RITL/CellLeaksTest这里，麻烦您给看一下，如果我什么地方错了，请指正，学习啦，3Q O(∩_∩)O

**Comment by gx2015** [comment]
我也遇到这个问题 找了好久 也不知道为什么没有被释放 我就写了一个很简单的demo：
- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.tableView.rowHeight = 60;
    [self.tableView registerClass:[UITableViewCell class] forCellReuseIdentifier:@"Cell"];
}

#pragma mark - Table view data source

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return 20;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"Cell" forIndexPath:indexPath];
    cell.textLabel.text = @"呵呵呵呵";
    
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    
    [self.navigationController popViewControllerAnimated:YES];
}

这个是详情控制器 点击cell代理自动pop出去 就会提示UITableViewCellContentView未被释放，如果点击导航条的默认返回按钮就没有这个问题 上一个控制器什么东西都没写只是跳转 也不知道是什么原因？

**Comment by Zepo** [comment]
恩，这个问题已经知道原因了，是因为 UITouch 持有了 cell，会在用户再次点击界面时释放，待 fix。

**Comment by JudithOnly** [comment]
后面是怎么解决的了？求教，我也遇到这个问题

**Comment by urmyfaith** [comment]
> 恩，这个问题已经知道原因了，是因为 UITouch 持有了 cell，会在用户再次点击界面时释放，待 fix。

@Zepo ?

这个有思路了吗?

**Comment by Zepo** [comment]
最新代码已 fix

**Comment by JavenZ** [comment]
Orz 请收下我的膝盖
