### ISSUE TITLE
Should UISwitch be in the whitelist?

### ISSUE THREAD

**Issue by itouch2** [Zepo/MLeaksFinder#36]
It seems that UISwitch can not be released (tested on iOS 10) in a right way. Should it be in the whitelist?

**Comment by Rannie** [comment]
same issue

**Comment by Zepo** [comment]
It's iOS 10's bug and we could put UISwitch in whitelist according to the iOS version.

**Comment by Jason318** [comment]
I dealt with this issue for two days...

**Comment by Zepo** [comment]
Has added 'UISwitch' to whitelist for iOS 10.
