### ISSUE TITLE
一个crash问题

### ISSUE THREAD

**Issue by SatanWoo** [Zepo/MLeaksFinder#37]
https://github.com/Zepo/MLeaksFinder/commit/66b071fafab2bbf0f21bc88f434197fc84c6a56d

您好，不知道在哪里请教问题比较合适。所以还借此请教下，这个commit的修改里，为什么采用对象比较就会crash。而采用对象的地址比较就没问题呢？

**Comment by Zepo** [comment]
objc_setAssociatedObject 的时候用的是 OBJC_ASSOCIATION_ASSIGN，是非持有的，对象可能会被释放。如果对象被释放了，那么 objc_getAssociatedObject 拿出来的时候会默认给对象发 retain 消息（ARC），导致 crash

**Comment by SatanWoo** [comment]
明白！谢谢！
