### ISSUE TITLE
使用过程中遇到这样一个Bug, 望作者解决

### ISSUE THREAD

**Issue by Tbwas** [Zepo/MLeaksFinder#39]
在一个ViewController中cellForRow的代理方法里创建一个UISwitch并作为cell的accessoryView,代码如下：
if (indexPath.row == 3) {
        UISwitch *s = [[UISwitch alloc] init];
        NSUserDefaults *userD = [NSUserDefaults standardUserDefaults];
        s.on = [[userD objectForKey:kWiFiKey] boolValue];
        [s addTarget:self action:@selector(promptOn:) forControlEvents:UIControlEventValueChanged];
        cell.accessoryView = s;
}

当退出当前controller时, 提示内存泄漏，提示如下：
In case that UISwitch should not be dealloced, override -willDealloc in UISwitch by returning NO.
View-ViewController stack: (
    LilySettingViewController,
    UIView,
    UIView,
    UITableView,
    UITableViewWrapperView,
    UITableViewCell,
    UISwitch
)

用Instruments工具分析无内存泄漏，并且当前controller的dealloc方法已执行。

**Comment by Zepo** [comment]
这个是 iOS 10 的系统 bug，iOS 10 的 UISwitch 确实是会泄漏的。最新代码已经把 UISwitch 加入白名单。
