### ISSUE TITLE
UIButton事件触发的 btn 会进入断言是什么原因呢？

### ISSUE THREAD

**Issue by iOSMaxZN** [Zepo/MLeaksFinder#4]

**Comment by Zepo** [comment]
btn 是什么意思？我想你问的跟 https://github.com/Zepo/MLeaksFinder/issues/3 这个可能是同个问题。

**Comment by iOSMaxZN** [comment]
UIButton *btn = [UIButton new];
 这个 btn 触发了pop事件或者 dismiss事件 这个btn就不会被释放掉 进入断言？
请问下这个 原因是什么呢？ 3Q

**Comment by Zepo** [comment]
看一下这个链接：https://github.com/Zepo/MLeaksFinder/issues/3

**Comment by iOSMaxZN** [comment]
明白了 谢谢
