### ISSUE TITLE
包含UITableViewCell 的Controller 手势pop

### ISSUE THREAD

**Issue by xmt0615** [Zepo/MLeaksFinder#41]
Retain Cycle: (
    "-> mockParent -> CartTableViewCell ",
    "-> __associated_object -> __NSDictionaryM ",
    "-> _AXTableViewCellInternal "
)
出现 这个 这个貌似是系统UIKit下边的一个类。。大神 我这是怎么了 求指教

**Comment by xmt0615** [comment]
经过测试 是 走dealloc方法的，难道是误报？ 手势侧滑 而且是 在cell上边 侧滑 才会出现这种情况

**Comment by Zepo** [comment]
经测试无没重现，确定几个问题：
1. 你用的是 swift 还是 OC
2. 报 leaks 后继续使用，有没有报 object deallocated

**Comment by xmt0615** [comment]
[MLeaksFinder测试.zip](https://github.com/Zepo/MLeaksFinder/files/577714/MLeaksFinder.zip)
测试的demo 麻烦您看下

**Comment by xmt0615** [comment]
@Zepo 只有模拟器才会出现问题 真机是正常的哦

**Comment by Zepo** [comment]
由于引进 Reveal 造成的循环引用，是 Reveal 的 bug
