### ISSUE TITLE
Xcode Release mode MLeaksFinder also work

### ISSUE THREAD

**Issue by sauchye** [Zepo/MLeaksFinder#43]
Hi:
   I just  pod ``MLeaksFinder``, when setting Xcode Release mode MLeaksFinder also work.

**Comment by mxpasser** [comment]
@Zepo ，工具很耗用。正想问这个问题，如果是release发布的时候，打出来的包如果有内存问题，那么是否还会弹出内存问题的提示？

**Comment by Zepo** [comment]
这个工具默认只在 debug 生效的

**Comment by Daemonson** [comment]
@mxpasser pod 'MLeaksFinder', :configurations => ['Debug']

**Comment by mxpasser** [comment]
@Daemonson Thanks!
