### ISSUE TITLE
没有出现以"View-ViewController stack:"为格式的闪退信息

### ISSUE THREAD

**Issue by TristenChen** [Zepo/MLeaksFinder#5]
闪退信息如下：
*** Assertion failure in -[CalendarVC assertNotDealloc], ..../Vendor/MLeaksFinder/NSObject+MemoryLeak.m:43
libc++abi.dylib: terminate_handler unexpectedly threw an exception

**Comment by Zepo** [comment]
已解决。现在在抛异常前先打 NSLog。

**Comment by TristenChen** [comment]
我试了一下，还是老样子

*** Assertion failure in -[SettingVC assertNotDealloc], /MLeaksFinder/NSObject+MemoryLeak.m:45
libc++abi.dylib: terminate_handler unexpectedly threw an exception
