### ISSUE TITLE
有一个页面pop之后代码crash,全局断点定位到这里NSGetSizeAndAlignment(typeEncoding.c_str(),...

### ISSUE THREAD

**Issue by WangGuibin** [Zepo/MLeaksFinder#66]
![71a084db-a713-4600-8300-107f9d4120bf](https://user-images.githubusercontent.com/15259130/29237744-564e74a4-7f57-11e7-833e-7c8922f6a062.png)
希望大佬们能解决这个问题。

**Comment by WangGuibin** [comment]
哎😌 是全局断点,这个坎👀,把全局断点去掉就好了~ 😌 抖机灵了

**Comment by hongfenglt** [comment]
所以这个问题除了去掉全局断点应该怎么解决？
