### ISSUE TITLE
可否增加UIViewController的addChildViewController和removeChildController的管理呢?

### ISSUE THREAD

**Issue by JianboYan** [Zepo/MLeaksFinder#8]
如题, 因为有些页面是用的那两个方法添加和移出的, 希望可以拓展这个库的能力

**Comment by Zepo** [comment]
在我们自己的项目中一般 childViewController 会通过成员变量的方式持有，方便反复地 add 和 remove，这种情况下 removeChildController 也不会释放。不知道你们使用 childViewController 的习惯是怎样的？或者可以加个开关，控制是否监测 childViewController

**Comment by MoZhouqi** [comment]
可以在检测应该被释放的 view controller 的同时递归遍历其 child view controller 的释放情况。

**Comment by Zepo** [comment]
目前已经在 view controller 释放的时候遍历 childViewControllers，但对于 removeFromParentViewController 的情况没有监测是否释放。
