### ISSUE TITLE
按钮leaks问题；gitSpecs问题；

### ISSUE THREAD

**Issue by fightrain** [Zepo/MLeaksFinder#9]
在pushed页面里添加按钮，按钮事件为执行pop。回到上一个页面后，如果没有屏幕interaction则报uibutton被持有，但controller被正确释放。此处应该是苹果的bug，但MLeaksFinder中可能还未添加处理。（SB和代码添加的button都有这个问题。由此推向所有UIControl相关的子类都有该问题，类似UIGesture已验证，但popGesture没问题）
另外，MLeaksFinder目前还未支持gitSpecs的搜索查询，引用pod成问题。

**Comment by Zepo** [comment]
podspec 已加上，UIButton 报泄露与 https://github.com/Zepo/MLeaksFinder/issues/16 重复。
